<h5 ><b><italic></italic>machine learning is turning thigs(data) into numbers, and finding patterns in those numbers</h5>

In [3]:
import torch
import math
import numpy as np
import pandas 
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())
def num_of_elements(t):
    if type(t)!=torch.Tensor:
        print(f"not a tensor. see the type {type(t)}")
        return
    return len(torch.flatten(t))

2.0.1
False


In [4]:
scaler=torch.tensor([[1,2],[2,3]])
print(scaler)
print(scaler.ndim)
print(scaler.item)


tensor([[1, 2],
        [2, 3]])
2
<built-in method item of Tensor object at 0x14cfecfe0>


In [5]:
vector=torch.tensor([[[1,2],[2,1]]])
vector

tensor([[[1, 2],
         [2, 1]]])

In [6]:
def rand_arr(rows,cols):
    res=[]
    if rows:
        for i in range(rows):
            temp=[]
            for j in range(cols):
                temp.append(np.random.randint(0,100))
            res.append(temp)
        return res
t=rand_arr(2,3)
t1=torch.Tensor(t)
t1

tensor([[68., 30., 16.],
        [92., 83., 34.]])

In [7]:
#pytorch way
t=torch.rand((3,3,3))
#create a tensor with random values of integers
t1=torch.randint(0,10,(3,3,3))
t1
img_temp=torch.rand((1080,1080,3))
img_temp

tensor([[[0.3723, 0.0135, 0.4602],
         [0.8010, 0.3759, 0.5991],
         [0.6455, 0.6819, 0.0731],
         ...,
         [0.8923, 0.0335, 0.7516],
         [0.7840, 0.4846, 0.6075],
         [0.7337, 0.3186, 0.1265]],

        [[0.4578, 0.3863, 0.7406],
         [0.8957, 0.3421, 0.5759],
         [0.3932, 0.9641, 0.7424],
         ...,
         [0.0534, 0.1044, 0.2016],
         [0.8003, 0.3686, 0.0900],
         [0.1872, 0.2021, 0.0835]],

        [[0.1494, 0.4527, 0.6208],
         [0.3318, 0.0562, 0.7353],
         [0.7532, 0.6178, 0.5745],
         ...,
         [0.8500, 0.6616, 0.8610],
         [0.5807, 0.5403, 0.6349],
         [0.9253, 0.8363, 0.3380]],

        ...,

        [[0.7429, 0.1255, 0.8077],
         [0.5679, 0.8568, 0.3762],
         [0.6893, 0.2480, 0.3590],
         ...,
         [0.8522, 0.0399, 0.5037],
         [0.6434, 0.2317, 0.9448],
         [0.0499, 0.0677, 0.9664]],

        [[0.5119, 0.0095, 0.8744],
         [0.2871, 0.9810, 0.4979],
         [0.

In [8]:
z=torch.zeros(2,3)
print(z)
o=torch.ones(2,3)
print(o)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [9]:
#allow to use like this
torch.tensor([1,int('23'),9.0], dtype=torch.float32, device='cpu', requires_grad=False)
# and not like this
# torch.tensor([1,'23',9.0])

tensor([ 1., 23.,  9.])

In [10]:
tensor32=torch.rand(3, 2,dtype=torch.float32)
print(tensor32,'\n',tensor32.dtype)
print('-'*100)
tensor16=torch.rand(3,2,dtype=torch.float16)
print(tensor16,'\n',tensor16.dtype)
print('-'*100)
mul_tensor=tensor32*tensor16
print(mul_tensor,'\n',mul_tensor.dtype)
print('-'*100)
int_tensor=torch.randint(0,10,(3,2))
print(int_tensor,'\n',int_tensor.dtype)

tensor([[0.8458, 0.6145],
        [0.0536, 0.1652],
        [0.6095, 0.3717]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[0.2954, 0.2090],
        [0.3086, 0.0615],
        [0.6582, 0.3472]], dtype=torch.float16) 
 torch.float16
----------------------------------------------------------------------------------------------------
tensor([[0.2498, 0.1284],
        [0.0165, 0.0102],
        [0.4012, 0.1290]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[3, 0],
        [9, 5],
        [8, 5]]) 
 torch.int64


In [11]:

print(t1[0])
print(t1[0]*t1[0])
print(t1[0])
t3=torch.rand(2,3)*100
print(t3)
print(np.int8(t3))

tensor([[9, 9, 5],
        [0, 4, 1],
        [6, 9, 7]])
tensor([[81, 81, 25],
        [ 0, 16,  1],
        [36, 81, 49]])
tensor([[9, 9, 5],
        [0, 4, 1],
        [6, 9, 7]])
tensor([[ 0.5501, 41.7304, 60.9480],
        [44.7685, 19.5094, 57.5136]])
[[ 0 41 60]
 [44 19 57]]


In [12]:
a=100
b=a+1
c=b+1
d=c+1
t4=torch.rand(a,b,c,d)*100
print(len(t4.flatten()))
for i in range(1000):
    t5=t4*t4
#it took 27.7 sec to do 1000 like this


106110600


In [13]:
for i in range(1000):
    t5=torch.mul(t4,t4)

1. it took 27.7 sec to do 1000 like this :t4*t4
2. it took 26.9 sec to do 100 like torch.mul(t4,t4)
3. conclusion : not  very big imporovment 

In [14]:
a1=np.arange(1,10)
a2=np.arange(10,19)
t6=torch.tensor(a1)
t7=torch.tensor(a2)
t8=(torch.mul(t6,t7))
print(f"{t6}\n{t7}\n{t8}")
t9=t8.reshape(3,3)
print(t9)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18])
tensor([ 10,  22,  36,  52,  70,  90, 112, 136, 162])
tensor([[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]])


In [15]:


t10=torch.rand(1,8,25)
print(num_of_elements(t10))
t11=torch.rand(2,4,25)
t12=t10.reshape_as(t11)
print(t12)


200
tensor([[[9.4906e-01, 7.3698e-01, 1.1030e-01, 4.7533e-01, 4.2643e-01,
          8.8670e-01, 3.3270e-01, 8.8512e-01, 8.8647e-01, 6.4447e-01,
          3.3993e-01, 3.4926e-01, 6.3579e-01, 4.8135e-02, 1.7880e-02,
          6.1791e-01, 3.0991e-01, 1.4772e-01, 5.9903e-01, 4.2894e-01,
          6.0534e-01, 1.0485e-01, 9.6305e-01, 7.2096e-01, 3.0883e-02],
         [1.6279e-01, 2.1719e-01, 6.2704e-01, 5.8596e-01, 7.1115e-01,
          8.1044e-01, 2.9675e-01, 2.8995e-02, 4.4053e-01, 7.9631e-02,
          8.1762e-01, 8.2947e-02, 3.6626e-01, 6.2688e-01, 4.6676e-01,
          4.9981e-02, 8.0117e-02, 1.0872e-01, 4.6920e-01, 4.9767e-01,
          4.2980e-01, 3.1204e-01, 9.2212e-01, 6.2769e-01, 1.0662e-01],
         [1.5705e-01, 8.4595e-01, 9.8373e-01, 2.2332e-01, 9.5178e-01,
          8.2753e-01, 9.6286e-02, 4.0435e-01, 7.6488e-01, 7.0403e-01,
          4.1985e-01, 7.2887e-01, 7.4652e-01, 9.6244e-01, 1.4342e-01,
          6.3230e-02, 9.5831e-01, 5.2908e-01, 8.4643e-02, 9.9511e-01,
          7.80

In [19]:

a=100
b=a*10
c=b*10
d=c*10
t13=torch.rand(c,d)
t14=torch.rand(d,c)
t15=torch.matmul(t13,t14)

/var/folders/hh/bn85jql94k9dkgccvt0vbxf40000gn/T/ipykernel_2846/4259908433.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


In [33]:
# t16=t15.clone.detach()
# t16=torch.tensor(t15,dtype=torch.int32)

/var/folders/hh/bn85jql94k9dkgccvt0vbxf40000gn/T/ipykernel_2846/4259908433.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t16=torch.tensor(t15,dtype=torch.int32)


In [29]:
t16

tensor([], dtype=torch.int32)