<h5 ><b><italic></italic>machine learning is turning thigs(data) into numbers, and finding patterns in those numbers</h5>

In [18]:
import torch
import math
import numpy as np
import pandas 
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())
def num_of_elements(t):
    if type(t)!=torch.Tensor:
        print(f"not a tensor. see the type {type(t)}")
        return
    return len(torch.flatten(t))

2.0.1
False


In [19]:
scaler=torch.tensor([[1,2],[2,3]])
print(scaler)
print(scaler.ndim)
print(scaler.item)


tensor([[1, 2],
        [2, 3]])
2
<built-in method item of Tensor object at 0x17f1536a0>


In [20]:
vector=torch.tensor([[[1,2],[2,1]]])
vector

tensor([[[1, 2],
         [2, 1]]])

In [21]:
def rand_arr(rows,cols):
    res=[]
    if rows:
        for i in range(rows):
            temp=[]
            for j in range(cols):
                temp.append(np.random.randint(0,100))
            res.append(temp)
        return res
t=rand_arr(2,3)
t1=torch.Tensor(t)
t1

tensor([[24., 60., 19.],
        [72., 35.,  9.]])

In [22]:
#pytorch way
t=torch.rand((3,3,3))
#create a tensor with random values of integers
t1=torch.randint(0,10,(3,3,3))
t1
img_temp=torch.rand((1080,1080,3))
img_temp

tensor([[[0.4280, 0.5172, 0.3999],
         [0.6190, 0.4591, 0.7215],
         [0.4798, 0.0522, 0.3829],
         ...,
         [0.0890, 0.6036, 0.3313],
         [0.7193, 0.2600, 0.6857],
         [0.2104, 0.9821, 0.2519]],

        [[0.5268, 0.4899, 0.4493],
         [0.8221, 0.5755, 0.1139],
         [0.5598, 0.7955, 0.7806],
         ...,
         [0.3046, 0.8472, 0.6431],
         [0.5935, 0.1386, 0.4226],
         [0.7884, 0.4996, 0.6049]],

        [[0.1228, 0.9128, 0.1091],
         [0.1957, 0.9297, 0.0655],
         [0.5345, 0.0035, 0.4794],
         ...,
         [0.8819, 0.6486, 0.0096],
         [0.7419, 0.0014, 0.2439],
         [0.8069, 0.1204, 0.6884]],

        ...,

        [[0.0868, 0.0709, 0.9433],
         [0.0403, 0.4429, 0.1102],
         [0.2234, 0.9296, 0.3387],
         ...,
         [0.7883, 0.4558, 0.9331],
         [0.9458, 0.0394, 0.1119],
         [0.7142, 0.6248, 0.3035]],

        [[0.6099, 0.9344, 0.6423],
         [0.7486, 0.7657, 0.0214],
         [0.

In [23]:
z=torch.zeros(2,3)
print(z)
o=torch.ones(2,3)
print(o)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [24]:
#allow to use like this
torch.tensor([1,int('23'),9.0], dtype=torch.float32, device='cpu', requires_grad=False)
# and not like this
# torch.tensor([1,'23',9.0])

tensor([ 1., 23.,  9.])

In [25]:
tensor32=torch.rand(3, 2,dtype=torch.float32)
print(tensor32,'\n',tensor32.dtype)
print('-'*100)
tensor16=torch.rand(3,2,dtype=torch.float16)
print(tensor16,'\n',tensor16.dtype)
print('-'*100)
mul_tensor=tensor32*tensor16
print(mul_tensor,'\n',mul_tensor.dtype)
print('-'*100)
int_tensor=torch.randint(0,10,(3,2))
print(int_tensor,'\n',int_tensor.dtype)

tensor([[0.0677, 0.8132],
        [0.2942, 0.9856],
        [0.5541, 0.8044]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[0.4453, 0.2632],
        [0.0996, 0.4326],
        [0.1191, 0.2910]], dtype=torch.float16) 
 torch.float16
----------------------------------------------------------------------------------------------------
tensor([[0.0301, 0.2140],
        [0.0293, 0.4264],
        [0.0660, 0.2341]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[7, 6],
        [4, 5],
        [4, 8]]) 
 torch.int64


In [26]:

print(t1[0])
print(t1[0]*t1[0])
print(t1[0])
t3=torch.rand(2,3)*100
print(t3)
print(np.int8(t3))

tensor([[3, 8, 5],
        [4, 6, 2],
        [3, 3, 7]])
tensor([[ 9, 64, 25],
        [16, 36,  4],
        [ 9,  9, 49]])
tensor([[3, 8, 5],
        [4, 6, 2],
        [3, 3, 7]])
tensor([[65.1182, 70.3372, 90.6279],
        [17.5383, 77.9241,  3.7910]])
[[65 70 90]
 [17 77  3]]


In [27]:
a=100
b=a+1
c=b+1
d=c+1
t4=torch.rand(a,b,c,d)*100
print(len(t4.flatten()))
for i in range(1000):
    t5=t4*t4
#it took 27.7 sec to do 1000 like this


106110600


In [ ]:
for i in range(1000):
    t5=torch.mul(t4,t4)

1. it took 27.7 sec to do 1000 like this :t4*t4
2. it took 26.9 sec to do 100 like torch.mul(t4,t4)
3. conclusion : not  very big imporovment 

In [ ]:
a1=np.arange(1,10)
a2=np.arange(10,19)
t6=torch.tensor(a1)
t7=torch.tensor(a2)
t8=(torch.mul(t6,t7))
print(f"{t6}\n{t7}\n{t8}")
t9=t8.reshape(3,3)
print(t9)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18])
tensor([ 10,  22,  36,  52,  70,  90, 112, 136, 162])
tensor([[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]])


In [ ]:


t10=torch.rand(1,8,25)
print(num_of_elements(t10))
t11=torch.rand(2,4,25)
t12=t10.reshape_as(t11)
print(t12)


200
tensor([[[0.2731, 0.1552, 0.9708, 0.3784, 0.7722, 0.8403, 0.6993, 0.3197,
          0.6122, 0.7681, 0.7625, 0.0897, 0.5007, 0.2010, 0.1627, 0.3813,
          0.2623, 0.4774, 0.1252, 0.6627, 0.0555, 0.7289, 0.9863, 0.5747,
          0.9447],
         [0.0197, 0.7339, 0.6145, 0.3780, 0.4481, 0.4388, 0.2121, 0.7787,
          0.1411, 0.0581, 0.8863, 0.6576, 0.2577, 0.0190, 0.4783, 0.0755,
          0.1534, 0.7465, 0.7229, 0.0794, 0.6526, 0.3090, 0.6705, 0.1885,
          0.8103],
         [0.0881, 0.5724, 0.3858, 0.0982, 0.2042, 0.2213, 0.1609, 0.8410,
          0.0995, 0.8031, 0.9674, 0.5416, 0.8463, 0.0411, 0.2862, 0.8664,
          0.6257, 0.8469, 0.5920, 0.0088, 0.5086, 0.7501, 0.4508, 0.1866,
          0.7967],
         [0.3699, 0.2938, 0.6768, 0.3866, 0.1787, 0.7525, 0.8024, 0.8731,
          0.7379, 0.8673, 0.6453, 0.6464, 0.1762, 0.5786, 0.6548, 0.1692,
          0.4482, 0.3758, 0.3279, 0.7518, 0.8812, 0.8454, 0.9795, 0.3197,
          0.3753]],

        [[0.2539, 0.8350, 0.72

In [ ]:

a=100
b=a*10
c=b*10
d=c*10
t13=torch.rand(c,d)
t14=torch.rand(d,c)
t15=torch.matmul(t13,t14)

/var/folders/hh/bn85jql94k9dkgccvt0vbxf40000gn/T/ipykernel_2846/4259908433.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


In [ ]:
# t16=t15.clone.detach()
t16=torch.tensor(t15,dtype=torch.int32)

/var/folders/hh/bn85jql94k9dkgccvt0vbxf40000gn/T/ipykernel_10327/4259908433.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t16=torch.tensor(t15,dtype=torch.int32)


In [ ]:
np1=np.random.randint(1,10,30)
t17=torch.tensor(np1)
t17=t17.reshape([2,3,5])
# print(t17)
# print(t17.T)
# print(torch.mm(t17,t17.T))


In [ ]:
#aggregtion
#1.min
t18=torch.randint(1,100,(2,3,4))
print(t18)
print(f" min: {t18.min()}\n max: {t18.max()}\n mean: {t18.mean(dtype=torch.float16)}\n meadian: {t18.median()}")

tensor([[[58,  4, 24, 23],
         [78, 18, 79, 33],
         [39, 35,  9, 33]],

        [[52, 20, 58, 76],
         [86, 87,  8,  5],
         [94, 49, 69, 59]]])
 min: 4
 max: 94
 mean: 45.65625
 meadian: 39
