<h5 ><b><italic></italic>machine learning is turning thigs(data) into numbers, and finding patterns in those numbers</h5>

In [1]:
import torch
import math
import numpy as np
import pandas 
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())
def num_of_elements(t):
    if type(t)!=torch.Tensor:
        print(f"not a tensor. see the type {type(t)}")
        return
    return len(torch.flatten(t))

2.0.1
False


In [67]:
scaler=torch.tensor([[1,2],[2,3]])
print(scaler)
print(scaler.ndim)
print(scaler.item)


tensor([[1, 2],
        [2, 3]])
2
<built-in method item of Tensor object at 0x14e8ed3a0>


In [68]:
vector=torch.tensor([[[1,2],[2,1]]])
vector

tensor([[[1, 2],
         [2, 1]]])

In [69]:
def rand_arr(rows,cols):
    res=[]
    if rows:
        for i in range(rows):
            temp=[]
            for j in range(cols):
                temp.append(np.random.randint(0,100))
            res.append(temp)
        return res
t=rand_arr(2,3)
t1=torch.Tensor(t)
t1

tensor([[76., 90., 82.],
        [68.,  6., 38.]])

In [70]:
#pytorch way
t=torch.rand((3,3,3))
#create a tensor with random values of integers
t1=torch.randint(0,10,(3,3,3))
t1
img_temp=torch.rand((1080,1080,3))
img_temp

tensor([[[0.9077, 0.1045, 0.7447],
         [0.4996, 0.6791, 0.6251],
         [0.1415, 0.1732, 0.5672],
         ...,
         [0.4698, 0.0271, 0.8386],
         [0.1441, 0.0920, 0.3441],
         [0.9565, 0.9096, 0.5314]],

        [[0.2350, 0.2594, 0.5297],
         [0.0427, 0.0309, 0.9759],
         [0.6257, 0.2764, 0.8041],
         ...,
         [0.5606, 0.3108, 0.6786],
         [0.5371, 0.5606, 0.1689],
         [0.1597, 0.0837, 0.6576]],

        [[0.2442, 0.8374, 0.5586],
         [0.9787, 0.9377, 0.3923],
         [0.1707, 0.6913, 0.8506],
         ...,
         [0.4960, 0.8099, 0.4155],
         [0.0717, 0.2750, 0.3707],
         [0.6053, 0.3082, 0.5786]],

        ...,

        [[0.4245, 0.8448, 0.3641],
         [0.9982, 0.0517, 0.8296],
         [0.7257, 0.5624, 0.6672],
         ...,
         [0.8256, 0.4279, 0.0276],
         [0.3938, 0.4910, 0.6703],
         [0.9248, 0.7888, 0.8625]],

        [[0.2737, 0.6866, 0.1737],
         [0.3654, 0.2587, 0.1059],
         [0.

In [71]:
z=torch.zeros(2,3)
print(z)
o=torch.ones(2,3)
print(o)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [72]:
#allow to use like this
torch.tensor([1,int('23'),9.0], dtype=torch.float32, device='cpu', requires_grad=False)
# and not like this
# torch.tensor([1,'23',9.0])

tensor([ 1., 23.,  9.])

In [73]:
tensor32=torch.rand(3, 2,dtype=torch.float32)
print(tensor32,'\n',tensor32.dtype)
print('-'*100)
tensor16=torch.rand(3,2,dtype=torch.float16)
print(tensor16,'\n',tensor16.dtype)
print('-'*100)
mul_tensor=tensor32*tensor16
print(mul_tensor,'\n',mul_tensor.dtype)
print('-'*100)
int_tensor=torch.randint(0,10,(3,2))
print(int_tensor,'\n',int_tensor.dtype)

tensor([[0.4104, 0.2331],
        [0.1790, 0.2572],
        [0.2963, 0.6600]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[0.2441, 0.1519],
        [0.8423, 0.0928],
        [0.9468, 0.0420]], dtype=torch.float16) 
 torch.float16
----------------------------------------------------------------------------------------------------
tensor([[0.1002, 0.0354],
        [0.1507, 0.0239],
        [0.2806, 0.0277]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[2, 6],
        [2, 5],
        [0, 3]]) 
 torch.int64


In [74]:

print(t1[0])
print(t1[0]*t1[0])
print(t1[0])
t3=torch.rand(2,3)*100
print(t3)
print(np.int8(t3))

tensor([[1, 0, 6],
        [3, 1, 3],
        [2, 1, 0]])
tensor([[ 1,  0, 36],
        [ 9,  1,  9],
        [ 4,  1,  0]])
tensor([[1, 0, 6],
        [3, 1, 3],
        [2, 1, 0]])
tensor([[58.9414, 21.0332, 79.6358],
        [11.4276, 12.4200, 60.4879]])
[[58 21 79]
 [11 12 60]]


In [75]:
a=100
b=a+1
c=b+1
d=c+1
t4=torch.rand(a,b,c,d)*100
print(len(t4.flatten()))
for i in range(1000):
    t5=t4*t4
#it took 27.7 sec to do 1000 like this


106110600


In [76]:
for i in range(1000):
    t5=torch.mul(t4,t4)

1. it took 27.7 sec to do 1000 like this :t4*t4
2. it took 26.9 sec to do 100 like torch.mul(t4,t4)
3. conclusion : not  very big imporovment 

In [77]:
a1=np.arange(1,10)
a2=np.arange(10,19)
t6=torch.tensor(a1)
t7=torch.tensor(a2)
t8=(torch.mul(t6,t7))
print(f"{t6}\n{t7}\n{t8}")
t9=t8.reshape(3,3)
print(t9)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18])
tensor([ 10,  22,  36,  52,  70,  90, 112, 136, 162])
tensor([[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]])


In [78]:


t10=torch.rand(1,8,25)
print(num_of_elements(t10))
t11=torch.rand(2,4,25)
t12=t10.reshape_as(t11)
print(t12)


200
tensor([[[0.5632, 0.8233, 0.9791, 0.6955, 0.6665, 0.6708, 0.1815, 0.3568,
          0.7814, 0.1015, 0.1477, 0.7449, 0.3426, 0.7536, 0.1002, 0.7145,
          0.1630, 0.2066, 0.7470, 0.7690, 0.6106, 0.3493, 0.7537, 0.4251,
          0.6285],
         [0.6489, 0.8342, 0.9064, 0.1848, 0.9290, 0.3348, 0.5851, 0.0142,
          0.5811, 0.4519, 0.5135, 0.8939, 0.0832, 0.1713, 0.6563, 0.4261,
          0.9550, 0.9893, 0.0487, 0.8869, 0.6498, 0.4467, 0.6054, 0.7912,
          0.4391],
         [0.2084, 0.7804, 0.6228, 0.9408, 0.8661, 0.0863, 0.3834, 0.7536,
          0.6511, 0.6006, 0.8070, 0.8479, 0.1209, 0.4720, 0.2614, 0.9801,
          0.7603, 0.6216, 0.9354, 0.3656, 0.4982, 0.7260, 0.7928, 0.2941,
          0.4957],
         [0.4767, 0.2943, 0.7721, 0.7916, 0.9087, 0.1430, 0.8541, 0.6890,
          0.7539, 0.1084, 0.7381, 0.2748, 0.6152, 0.0021, 0.3165, 0.5573,
          0.2174, 0.7489, 0.6759, 0.2777, 0.4595, 0.6410, 0.7300, 0.9881,
          0.6119]],

        [[0.2898, 0.7279, 0.92

In [79]:

a=100
b=a*10
c=b*10
d=c*10
t13=torch.rand(c,d)
t14=torch.rand(d,c)
t15=torch.matmul(t13,t14)

KeyboardInterrupt: 

/var/folders/hh/bn85jql94k9dkgccvt0vbxf40000gn/T/ipykernel_2846/4259908433.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


In [ ]:
# t16=t15.clone.detach()
t16=torch.tensor(t15,dtype=torch.int32)

/var/folders/hh/bn85jql94k9dkgccvt0vbxf40000gn/T/ipykernel_2846/4259908433.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  t16=torch.tensor(t15,dtype=torch.int32)


In [2]:
np1=np.random.randint(1,10,30)
t17=torch.tensor(np1)
t17=t17.reshape([2,3,5])
# print(t17)
# print(t17.T)
# print(torch.mm(t17,t17.T))

/var/folders/hh/bn85jql94k9dkgccvt0vbxf40000gn/T/ipykernel_8289/2745301900.py:6: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1682343686130/work/aten/src/ATen/native/TensorShape.cpp:3575.)
  print(torch.mm(t17,t17.T))


RuntimeError: self must be a matrix