<h5 ><b><italic></italic>machine learning is turning thigs(data) into numbers, and finding patterns in those numbers</h5>

In [2]:
import torch
import numpy as np
import pandas 
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())

2.0.1
False


In [11]:
scaler=torch.tensor([[1,2],[2,3]])
print(scaler)
print(scaler.ndim)
print(scaler.item)


tensor([[1, 2],
        [2, 3]])
2
<built-in method item of Tensor object at 0x15f5a9b20>


In [17]:
vector=torch.tensor([[[1,2],[2,1]]])
vector

tensor([[[1, 2],
         [2, 1]]])

/var/folders/hh/bn85jql94k9dkgccvt0vbxf40000gn/T/ipykernel_72896/3626280825.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  a=np.random.random_integers(0,10)


1

In [69]:
def rand_arr(rows,cols):
    res=[]
    if rows:
        for i in range(rows):
            temp=[]
            for j in range(cols):
                temp.append(np.random.randint(0,100))
            res.append(temp)
        return res
t=rand_arr(2,3)
t1=torch.Tensor(t)
t1

tensor([[25., 45., 87.],
        [98., 52.,  8.]])

In [93]:
#pytorch way
t=torch.rand((3,3,3))
#create a tensor with random values of integers
t1=torch.randint(0,10,(3,3,3))
t1
img_temp=torch.rand((1080,1080,3))
img_temp

tensor([[[0.1170, 0.8753, 0.6305],
         [0.0492, 0.7569, 0.2246],
         [0.3549, 0.4659, 0.7536],
         ...,
         [0.2515, 0.0075, 0.8882],
         [0.4874, 0.9744, 0.3138],
         [0.2258, 0.2559, 0.2712]],

        [[0.7680, 0.4395, 0.2753],
         [0.6174, 0.6327, 0.0859],
         [0.6787, 0.9035, 0.5848],
         ...,
         [0.0239, 0.4203, 0.0404],
         [0.4959, 0.6505, 0.0092],
         [0.0062, 0.7776, 0.7717]],

        [[0.2305, 0.2556, 0.3916],
         [0.9741, 0.9292, 0.0335],
         [0.1336, 0.1359, 0.1259],
         ...,
         [0.8121, 0.7337, 0.0246],
         [0.3956, 0.9096, 0.7628],
         [0.0982, 0.0058, 0.1031]],

        ...,

        [[0.6777, 0.0340, 0.2653],
         [0.7490, 0.8149, 0.9989],
         [0.9103, 0.3248, 0.3821],
         ...,
         [0.9958, 0.1034, 0.9198],
         [0.0650, 0.3282, 0.2778],
         [0.8871, 0.2215, 0.9054]],

        [[0.0465, 0.8799, 0.1541],
         [0.5313, 0.9580, 0.2733],
         [0.

In [94]:
z=torch.zeros(2,3)
print(z)
o=torch.ones(2,3)
print(o)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [96]:
#allow to use like this
torch.tensor([1,int('23'),9.0], dtype=torch.float32, device='cpu', requires_grad=False)
# and not like this
# torch.tensor([1,'23',9.0])

tensor([ 1., 23.,  9.])

In [22]:
tensor32=torch.rand(3, 2,dtype=torch.float32)
print(tensor32,'\n',tensor32.dtype)
print('-'*100)
tensor16=torch.rand(3,2,dtype=torch.float16)
print(tensor16,'\n',tensor16.dtype)
print('-'*100)
mul_tensor=tensor32*tensor16
print(mul_tensor,'\n',mul_tensor.dtype)
print('-'*100)
int_tensor=torch.randint(0,10,(3,2))
print(int_tensor,'\n',int_tensor.dtype)

tensor([[0.8985, 0.0644],
        [0.2164, 0.1901],
        [0.9161, 0.5406]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[0.3271, 0.4668],
        [0.4414, 0.2588],
        [0.5215, 0.9355]], dtype=torch.float16) 
 torch.float16
----------------------------------------------------------------------------------------------------
tensor([[0.2939, 0.0300],
        [0.0955, 0.0492],
        [0.4777, 0.5057]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[7, 1],
        [8, 3],
        [7, 6]]) 
 torch.int64
