<h5 ><b><italic></italic>machine learning is turning thigs(data) into numbers, and finding patterns in those numbers</h5>

In [23]:
import torch
import numpy as np
import pandas 
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())

2.0.1
False


In [24]:
scaler=torch.tensor([[1,2],[2,3]])
print(scaler)
print(scaler.ndim)
print(scaler.item)


tensor([[1, 2],
        [2, 3]])
2
<built-in method item of Tensor object at 0x15d8f54e0>


In [25]:
vector=torch.tensor([[[1,2],[2,1]]])
vector

tensor([[[1, 2],
         [2, 1]]])

In [26]:
def rand_arr(rows,cols):
    res=[]
    if rows:
        for i in range(rows):
            temp=[]
            for j in range(cols):
                temp.append(np.random.randint(0,100))
            res.append(temp)
        return res
t=rand_arr(2,3)
t1=torch.Tensor(t)
t1

tensor([[74., 29., 17.],
        [17., 98., 96.]])

In [27]:
#pytorch way
t=torch.rand((3,3,3))
#create a tensor with random values of integers
t1=torch.randint(0,10,(3,3,3))
t1
img_temp=torch.rand((1080,1080,3))
img_temp

tensor([[[0.5800, 0.1459, 0.5564],
         [0.6931, 0.1784, 0.8337],
         [0.6736, 0.7961, 0.8715],
         ...,
         [0.1983, 0.7695, 0.3675],
         [0.6206, 0.9410, 0.1889],
         [0.7023, 0.3649, 0.7902]],

        [[0.6169, 0.6363, 0.1882],
         [0.9949, 0.1601, 0.8504],
         [0.9454, 0.0095, 0.9830],
         ...,
         [0.0211, 0.3708, 0.7157],
         [0.1846, 0.6623, 0.7065],
         [0.0486, 0.3219, 0.4426]],

        [[0.8646, 0.3578, 0.0656],
         [0.9436, 0.2486, 0.7014],
         [0.9630, 0.3847, 0.3465],
         ...,
         [0.1135, 0.6134, 0.1061],
         [0.2144, 0.7641, 0.9249],
         [0.9774, 0.5740, 0.5275]],

        ...,

        [[0.4627, 0.6721, 0.3424],
         [0.2002, 0.7640, 0.4649],
         [0.0311, 0.3396, 0.8470],
         ...,
         [0.4717, 0.2197, 0.0980],
         [0.5928, 0.2580, 0.5672],
         [0.1993, 0.1842, 0.2356]],

        [[0.5023, 0.8080, 0.1573],
         [0.8634, 0.0324, 0.8753],
         [0.

In [28]:
z=torch.zeros(2,3)
print(z)
o=torch.ones(2,3)
print(o)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [29]:
#allow to use like this
torch.tensor([1,int('23'),9.0], dtype=torch.float32, device='cpu', requires_grad=False)
# and not like this
# torch.tensor([1,'23',9.0])

tensor([ 1., 23.,  9.])

In [30]:
tensor32=torch.rand(3, 2,dtype=torch.float32)
print(tensor32,'\n',tensor32.dtype)
print('-'*100)
tensor16=torch.rand(3,2,dtype=torch.float16)
print(tensor16,'\n',tensor16.dtype)
print('-'*100)
mul_tensor=tensor32*tensor16
print(mul_tensor,'\n',mul_tensor.dtype)
print('-'*100)
int_tensor=torch.randint(0,10,(3,2))
print(int_tensor,'\n',int_tensor.dtype)

tensor([[0.6643, 0.7321],
        [0.9160, 0.0618],
        [0.7788, 0.0597]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[0.8208, 0.3008],
        [0.1392, 0.7656],
        [0.9268, 0.3105]], dtype=torch.float16) 
 torch.float16
----------------------------------------------------------------------------------------------------
tensor([[0.5452, 0.2202],
        [0.1275, 0.0473],
        [0.7217, 0.0185]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[5, 8],
        [3, 5],
        [2, 3]]) 
 torch.int64


In [31]:
t1.device

device(type='cpu')