<h5 ><b><italic></italic>machine learning is turning thigs(data) into numbers, and finding patterns in those numbers</h5>

In [80]:
import torch
import math
import numpy as np
import pandas 
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())
def num_of_elements(t):
    if type(t)!=torch.Tensor:
        print(f"not a tensor. see the type {type(t)}")
        return
    return len(torch.flatten(t))

2.0.1
False


In [2]:
scaler=torch.tensor([[1,2],[2,3]])
print(scaler)
print(scaler.ndim)
print(scaler.item)


tensor([[1, 2],
        [2, 3]])
2
<built-in method item of Tensor object at 0x13f60eac0>


In [3]:
vector=torch.tensor([[[1,2],[2,1]]])
vector

tensor([[[1, 2],
         [2, 1]]])

In [4]:
def rand_arr(rows,cols):
    res=[]
    if rows:
        for i in range(rows):
            temp=[]
            for j in range(cols):
                temp.append(np.random.randint(0,100))
            res.append(temp)
        return res
t=rand_arr(2,3)
t1=torch.Tensor(t)
t1

tensor([[ 5., 41., 85.],
        [36., 51., 53.]])

In [5]:
#pytorch way
t=torch.rand((3,3,3))
#create a tensor with random values of integers
t1=torch.randint(0,10,(3,3,3))
t1
img_temp=torch.rand((1080,1080,3))
img_temp

tensor([[[0.6906, 0.9907, 0.6087],
         [0.0849, 0.5630, 0.9889],
         [0.4565, 0.9837, 0.3398],
         ...,
         [0.2728, 0.5198, 0.8279],
         [0.0896, 0.6942, 0.1848],
         [0.2672, 0.0535, 0.2069]],

        [[0.4071, 0.6216, 0.0756],
         [0.7940, 0.2744, 0.0876],
         [0.6263, 0.3943, 0.3084],
         ...,
         [0.7729, 0.3421, 0.0803],
         [0.0141, 0.1438, 0.1864],
         [0.1573, 0.6477, 0.5283]],

        [[0.7418, 0.5818, 0.9864],
         [0.8340, 0.4226, 0.1229],
         [0.8605, 0.2399, 0.7072],
         ...,
         [0.5214, 0.2891, 0.0416],
         [0.5794, 0.1093, 0.7145],
         [0.7178, 0.4826, 0.5445]],

        ...,

        [[0.0071, 0.8876, 0.9428],
         [0.2115, 0.4288, 0.8330],
         [0.3308, 0.5459, 0.7165],
         ...,
         [0.7204, 0.5195, 0.9481],
         [0.0615, 0.7726, 0.1284],
         [0.7373, 0.1074, 0.2114]],

        [[0.0128, 0.9433, 0.2315],
         [0.1195, 0.9399, 0.2538],
         [0.

In [6]:
z=torch.zeros(2,3)
print(z)
o=torch.ones(2,3)
print(o)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
#allow to use like this
torch.tensor([1,int('23'),9.0], dtype=torch.float32, device='cpu', requires_grad=False)
# and not like this
# torch.tensor([1,'23',9.0])

tensor([ 1., 23.,  9.])

In [8]:
tensor32=torch.rand(3, 2,dtype=torch.float32)
print(tensor32,'\n',tensor32.dtype)
print('-'*100)
tensor16=torch.rand(3,2,dtype=torch.float16)
print(tensor16,'\n',tensor16.dtype)
print('-'*100)
mul_tensor=tensor32*tensor16
print(mul_tensor,'\n',mul_tensor.dtype)
print('-'*100)
int_tensor=torch.randint(0,10,(3,2))
print(int_tensor,'\n',int_tensor.dtype)

tensor([[0.9271, 0.5410],
        [0.4399, 0.0125],
        [0.1010, 0.7970]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[0.8726, 0.2739],
        [0.4121, 0.4922],
        [0.1587, 0.1206]], dtype=torch.float16) 
 torch.float16
----------------------------------------------------------------------------------------------------
tensor([[0.8089, 0.1482],
        [0.1813, 0.0061],
        [0.0160, 0.0961]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[0, 4],
        [5, 6],
        [1, 0]]) 
 torch.int64


In [55]:

print(t1[0])
print(t1[0]*t1[0])
print(t1[0])
t3=torch.rand(2,3)*100
print(t3)
print(np.int8(t3))

tensor([[4, 3, 8],
        [4, 6, 3],
        [4, 9, 7]])
tensor([[16,  9, 64],
        [16, 36,  9],
        [16, 81, 49]])
tensor([[4, 3, 8],
        [4, 6, 3],
        [4, 9, 7]])
tensor([[87.4605, 31.1702, 53.6106],
        [70.9740, 94.5568, 43.9755]])
[[87 31 53]
 [70 94 43]]
CPU times: user 2.11 ms, sys: 1.52 ms, total: 3.63 ms
Wall time: 2.64 ms


In [65]:
a=100
b=a+1
c=b+1
d=c+1
t4=torch.rand(a,b,c,d)*100
print(len(t4.flatten()))
for i in range(1000):
    t5=t4*t4
#it took 27.7 sec to do 1000 like this


106110600


In [66]:
for i in range(1000):
    t5=torch.mul(t4,t4)

1. it took 27.7 sec to do 1000 like this :t4*t4
2. it took 26.9 sec to do 100 like torch.mul(t4,t4)
3. conclusion : not  very big imporovment 

In [56]:
a1=np.arange(1,10)
a2=np.arange(10,19)
t6=torch.tensor(a1)
t7=torch.tensor(a2)
t8=(torch.mul(t6,t7))
print(f"{t6}\n{t7}\n{t8}")
t9=t8.reshape(3,3)
print(t9)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18])
tensor([ 10,  22,  36,  52,  70,  90, 112, 136, 162])
tensor([[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]])


In [88]:


t10=torch.rand(1,8,25)
print(num_of_elements(t10))
t11=torch.rand(2,4,25)
t12=t10.reshape_as(t11)
print(t12)


200
tensor([[[0.2387, 0.9901, 0.6468, 0.0047, 0.7837, 0.1028, 0.7355, 0.9334,
          0.9413, 0.1020, 0.3224, 0.4860, 0.4804, 0.6077, 0.9421, 0.9604,
          0.2722, 0.0375, 0.7549, 0.8787, 0.6871, 0.9720, 0.5675, 0.7579,
          0.8533],
         [0.5496, 0.3905, 0.2124, 0.7106, 0.9708, 0.7095, 0.0430, 0.0179,
          0.9948, 0.9496, 0.6738, 0.9580, 0.0908, 0.1362, 0.2170, 0.4295,
          0.5510, 0.6583, 0.7039, 0.2153, 0.8372, 0.5144, 0.4806, 0.4492,
          0.6686],
         [0.9720, 0.9458, 0.5668, 0.3596, 0.5696, 0.5276, 0.7023, 0.0269,
          0.3165, 0.5911, 0.4826, 0.6425, 0.1995, 0.9940, 0.0584, 0.5395,
          0.5818, 0.8270, 0.9880, 0.1453, 0.3865, 0.7631, 0.8072, 0.5536,
          0.8264],
         [0.2096, 0.5483, 0.0627, 0.1791, 0.9504, 0.9812, 0.3072, 0.7723,
          0.1112, 0.5921, 0.6282, 0.1994, 0.4380, 0.6960, 0.2500, 0.7323,
          0.6575, 0.3030, 0.1322, 0.0202, 0.3967, 0.5767, 0.4232, 0.7945,
          0.1025]],

        [[0.5120, 0.8273, 0.33

In [108]:
t13=torch.rand(1,6)
t14=torch.rand(6,5)
# t14=t14.reshape_as(t13)
print(torch.matmul(t13,t14))

tensor([[0.3997, 0.8162, 0.9719, 0.7677, 0.5502]])
