<h5 ><b><italic></italic>machine learning is turning thigs(data) into numbers, and finding patterns in those numbers</h5>

In [16]:
import torch
import math
import numpy as np
import pandas 
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())

2.0.1
False


In [2]:
scaler=torch.tensor([[1,2],[2,3]])
print(scaler)
print(scaler.ndim)
print(scaler.item)


tensor([[1, 2],
        [2, 3]])
2
<built-in method item of Tensor object at 0x13f60eac0>


In [3]:
vector=torch.tensor([[[1,2],[2,1]]])
vector

tensor([[[1, 2],
         [2, 1]]])

In [4]:
def rand_arr(rows,cols):
    res=[]
    if rows:
        for i in range(rows):
            temp=[]
            for j in range(cols):
                temp.append(np.random.randint(0,100))
            res.append(temp)
        return res
t=rand_arr(2,3)
t1=torch.Tensor(t)
t1

tensor([[ 5., 41., 85.],
        [36., 51., 53.]])

In [5]:
#pytorch way
t=torch.rand((3,3,3))
#create a tensor with random values of integers
t1=torch.randint(0,10,(3,3,3))
t1
img_temp=torch.rand((1080,1080,3))
img_temp

tensor([[[0.6906, 0.9907, 0.6087],
         [0.0849, 0.5630, 0.9889],
         [0.4565, 0.9837, 0.3398],
         ...,
         [0.2728, 0.5198, 0.8279],
         [0.0896, 0.6942, 0.1848],
         [0.2672, 0.0535, 0.2069]],

        [[0.4071, 0.6216, 0.0756],
         [0.7940, 0.2744, 0.0876],
         [0.6263, 0.3943, 0.3084],
         ...,
         [0.7729, 0.3421, 0.0803],
         [0.0141, 0.1438, 0.1864],
         [0.1573, 0.6477, 0.5283]],

        [[0.7418, 0.5818, 0.9864],
         [0.8340, 0.4226, 0.1229],
         [0.8605, 0.2399, 0.7072],
         ...,
         [0.5214, 0.2891, 0.0416],
         [0.5794, 0.1093, 0.7145],
         [0.7178, 0.4826, 0.5445]],

        ...,

        [[0.0071, 0.8876, 0.9428],
         [0.2115, 0.4288, 0.8330],
         [0.3308, 0.5459, 0.7165],
         ...,
         [0.7204, 0.5195, 0.9481],
         [0.0615, 0.7726, 0.1284],
         [0.7373, 0.1074, 0.2114]],

        [[0.0128, 0.9433, 0.2315],
         [0.1195, 0.9399, 0.2538],
         [0.

In [6]:
z=torch.zeros(2,3)
print(z)
o=torch.ones(2,3)
print(o)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
#allow to use like this
torch.tensor([1,int('23'),9.0], dtype=torch.float32, device='cpu', requires_grad=False)
# and not like this
# torch.tensor([1,'23',9.0])

tensor([ 1., 23.,  9.])

In [8]:
tensor32=torch.rand(3, 2,dtype=torch.float32)
print(tensor32,'\n',tensor32.dtype)
print('-'*100)
tensor16=torch.rand(3,2,dtype=torch.float16)
print(tensor16,'\n',tensor16.dtype)
print('-'*100)
mul_tensor=tensor32*tensor16
print(mul_tensor,'\n',mul_tensor.dtype)
print('-'*100)
int_tensor=torch.randint(0,10,(3,2))
print(int_tensor,'\n',int_tensor.dtype)

tensor([[0.9271, 0.5410],
        [0.4399, 0.0125],
        [0.1010, 0.7970]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[0.8726, 0.2739],
        [0.4121, 0.4922],
        [0.1587, 0.1206]], dtype=torch.float16) 
 torch.float16
----------------------------------------------------------------------------------------------------
tensor([[0.8089, 0.1482],
        [0.1813, 0.0061],
        [0.0160, 0.0961]]) 
 torch.float32
----------------------------------------------------------------------------------------------------
tensor([[0, 4],
        [5, 6],
        [1, 0]]) 
 torch.int64


In [26]:
print(t1[0])
print(t1[0]*t1[0])
print(t1[0])
t3=torch.rand(2,3)*100
print(t3)
print(np.int8(t3))

tensor([[4, 3, 8],
        [4, 6, 3],
        [4, 9, 7]])
tensor([[16,  9, 64],
        [16, 36,  9],
        [16, 81, 49]])
tensor([[4, 3, 8],
        [4, 6, 3],
        [4, 9, 7]])
tensor([[96.6359, 86.1905, 10.8516],
        [38.9025,  0.9264, 85.4507]])
[[96 86 10]
 [38  0 85]]


In [36]:
a=100
b=a+1
c=b+1
d=c+1
t4=torch.rand(a,b,c,d)*100
t5=t4*t4
print(t5)


tensor([[[[4.2464e+03, 9.8163e+03, 2.5219e+03,  ..., 1.6505e+03,
           9.7523e+03, 2.2242e+02],
          [9.0235e+03, 2.7191e+01, 4.6042e+02,  ..., 6.9352e+03,
           3.2824e+03, 1.3256e+03],
          [2.9399e+03, 1.5269e+03, 6.1198e-02,  ..., 1.9329e+03,
           7.5309e+03, 1.9176e+03],
          ...,
          [1.0048e+03, 5.2223e+03, 2.3599e+03,  ..., 2.5041e+03,
           3.9081e+02, 7.9832e+03],
          [2.7198e+03, 7.7600e+03, 7.9733e+01,  ..., 5.4399e+02,
           1.5112e+03, 9.9936e+03],
          [2.9490e+02, 1.3110e+03, 2.6356e+02,  ..., 4.1985e+03,
           1.5322e+03, 6.6503e+03]],

         [[3.0175e+03, 3.6403e+03, 1.6125e+03,  ..., 5.4278e+03,
           2.3477e-01, 3.2040e+03],
          [3.7675e+01, 8.2978e+02, 8.3777e+03,  ..., 4.7886e+02,
           3.4323e+02, 4.2476e+00],
          [3.5865e+02, 2.1866e+03, 9.4532e+03,  ..., 3.3286e+03,
           1.5860e+03, 5.0135e+02],
          ...,
          [3.8842e+03, 1.6261e+03, 3.6359e+03,  ..., 2.4740

In [53]:
a1=np.arange(1,10)
a2=np.arange(10,19)
t6=torch.tensor(a1)
t7=torch.tensor(a2)
t8=(torch.mul(t6,t7))
print(f"{t6}\n{t7}\n{t8}")
t9=t8.reshape(3,3)
print(t9)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18])
tensor([ 10,  22,  36,  52,  70,  90, 112, 136, 162])
tensor([[ 10,  22,  36],
        [ 52,  70,  90],
        [112, 136, 162]])
