<h5 ><b><italic></italic>machine learning is turning thigs(data) into numbers, and finding patterns in those numbers</h5>

In [18]:
import torch
import numpy as np
import pandas 
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())

2.0.1
False


In [11]:
scaler=torch.tensor([[1,2],[2,3]])
print(scaler)
print(scaler.ndim)
print(scaler.item)


tensor([[1, 2],
        [2, 3]])
2
<built-in method item of Tensor object at 0x15f5a9b20>


In [17]:
vector=torch.tensor([[[1,2],[2,1]]])
vector

tensor([[[1, 2],
         [2, 1]]])

/var/folders/hh/bn85jql94k9dkgccvt0vbxf40000gn/T/ipykernel_72896/3626280825.py:1: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  a=np.random.random_integers(0,10)


1

In [69]:
def rand_arr(rows,cols):
    res=[]
    if rows:
        for i in range(rows):
            temp=[]
            for j in range(cols):
                temp.append(np.random.randint(0,100))
            res.append(temp)
        return res
t=rand_arr(2,3)
t1=torch.Tensor(t)
t1

tensor([[25., 45., 87.],
        [98., 52.,  8.]])

In [87]:
#pytorch way
t=torch.rand((3,3))
#create a tensor with random values of integers
t1=torch.randint(0,10,(3,3))
t1

tensor([[7, 1, 1],
        [8, 3, 2],
        [7, 0, 9]])