In [38]:
import torch
import numpy as np
print(torch.cuda.is_available()) 
print(torch.rand(2,2))

False
tensor([[0.8835, 0.8311],
        [0.2414, 0.9528]])


In [57]:
import math
x=torch.rand([2,3,4,5])*10
print(type(x))
y=torch.tensor([1,2])
dims=x.shape
x1=x.flatten()

for i in range(len(x1)):
    x1[i]=math.floor(x1[i])
x2=torch.Tensor(x1)
x2=x2.reshape(2,3,4,5)
x2

<class 'torch.Tensor'>


tensor([[[[7., 3., 7., 9., 0.],
          [7., 9., 8., 9., 3.],
          [7., 0., 8., 6., 7.],
          [3., 7., 7., 6., 4.]],

         [[1., 3., 0., 2., 0.],
          [1., 7., 3., 3., 1.],
          [3., 4., 1., 2., 1.],
          [7., 3., 5., 4., 5.]],

         [[9., 7., 3., 1., 0.],
          [5., 3., 5., 5., 8.],
          [8., 8., 0., 5., 7.],
          [9., 6., 4., 6., 1.]]],


        [[[2., 7., 1., 4., 4.],
          [4., 3., 6., 6., 7.],
          [3., 3., 0., 3., 1.],
          [0., 9., 1., 2., 5.]],

         [[7., 2., 2., 5., 5.],
          [5., 9., 5., 8., 1.],
          [9., 3., 5., 2., 4.],
          [7., 4., 3., 8., 4.]],

         [[1., 0., 2., 1., 5.],
          [8., 3., 4., 5., 3.],
          [0., 1., 4., 9., 8.],
          [7., 0., 2., 6., 1.]]]])

In [80]:
t1=torch.randint(1,10,(1,3))
t2=torch.randint(1,10,(3,3))
print(t1)
print(t2)
print(t1+t2)

tensor([[2, 2, 5]])
tensor([[3, 8, 9],
        [7, 7, 8],
        [2, 2, 4]])
tensor([[ 5, 10, 14],
        [ 9,  9, 13],
        [ 4,  4,  9]])
